server:
  port: 8080

spring:
  application:
    name: focason-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
    allow-circular-references: true
  cloud:
    gateway:
      routes:
        - id: focason-oauth2
          uri: lb://focason-oauth2
          predicates:
            - Path=/auth/**
        - id: focason-user
          uri: lb://focason-user
          predicates:
            - Path=/users/**

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://root:password@localhost:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
